sel4test-hw: skip x86 32-bit SMP + hyp
64-bit seems to be fine, but 32-bit does not even compile:
```
In file included from /github/workspace/kernel/include/arch/x86/arch/kernel/elf.h:10,
                   from /github/workspace/kernel/src/arch/x86/32/kernel/elf.c:7:
  /github/workspace/kernel/include/arch/x86/arch/32/mode/kernel/elf.h:41:28: error: unterminated argument list invoking macro "NODE_STATE"
     41 | } Elf32_Phdr_t, Elf_Phdr_t;
        |                            ^
```

This compile error also occurs for 15.0.0 seL4, so it is not a recent
regression.

Signed-off-by: Ivan Velickovic <i.velickovic@unsw.edu.au>